### ISSUE TITLE
Node has moved F_OK, R_OK etc

### ISSUE THREAD

**Issue by nevster** [davetemplin/async-file#4]
If I install typings for node 6, I get errors when compiling like this:
async-file/index.d.ts(2,121): error TS2305: Module '"fs"' has no exported member 'F_OK'

Looking at the node/index.d.ts I see they've now got this:
    interface Constants {
        F_OK: number;
        R_OK: number;
        etc
    }

Can you fix this?

**Comment by PS-davetemplin** [comment]
Yes, I will look into this today. Thank you so much for reporting the issue!

**Comment by davetemplin** [comment]
Fixed in version 2.0.2.

**Comment by nevster** [comment]
Awesome. Thanks Dave!
