### ISSUE TITLE
Feature req: Ability to also wrap alternative fs (f.x. memfs) for testing purposes

### ISSUE THREAD

**Issue by mmc41** [davetemplin/async-file#7]
I like async-file a lot (especially the full typescript support)... Would it be possible to use async-file to wrap alternative file system libs around like for instance memfs. It would make it so much nicer to test code that uses async-file for destructive operations like delete, if I could execute them in a virtual in-memory file system. Other use cases would be to use async-file to wrap fs-dropbox or something similar?

**Comment by mmc41** [comment]
A simple way to support multiple system libs, would be to export a factory method that take a filesystem as argument and returned a promised filesystem.

**Comment by PS-davetemplin** [comment]
So sorry for the late response. Sounds like a great idea. If you're still interested, maybe a pull request would help.

**Comment by PS-davetemplin** [comment]
Closing for now.
